from __future__ import annotations

ISSUE_CHEMICAL_INVALID = "CHEMICAL_INVALID"
ISSUE_REACTION_INCOMPATIBLE = "REACTION_INCOMPATIBLE"
ISSUE_REQUESTED_GROUPS_FAILED = "REQUESTED_GROUPS_FAILED"
ISSUE_GROUP1_MISSING = "GROUP1_MISSING"
ISSUE_GROUP2_MISSING = "GROUP2_MISSING"
ISSUE_PROPERTY_PREDICTION_FAILED = "PROPERTY_PREDICTION_FAILED"
ISSUE_TG_OUT_OF_RANGE = "TG_OUT_OF_RANGE"
ISSUE_ER_OUT_OF_RANGE = "ER_OUT_OF_RANGE"
